// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: rpcPoc.proto

package pocsuite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecPythonSerializeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Port string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Id   string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ExecPythonSerializeRequest) Reset() {
	*x = ExecPythonSerializeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcPoc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecPythonSerializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecPythonSerializeRequest) ProtoMessage() {}

func (x *ExecPythonSerializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcPoc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecPythonSerializeRequest.ProtoReflect.Descriptor instead.
func (*ExecPythonSerializeRequest) Descriptor() ([]byte, []int) {
	return file_rpcPoc_proto_rawDescGZIP(), []int{0}
}

func (x *ExecPythonSerializeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecPythonSerializeRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ExecPythonSerializeRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ExecPythonSerializeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResultByte struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ResultByte) Reset() {
	*x = ResultByte{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcPoc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultByte) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultByte) ProtoMessage() {}

func (x *ResultByte) ProtoReflect() protoreflect.Message {
	mi := &file_rpcPoc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultByte.ProtoReflect.Descriptor instead.
func (*ResultByte) Descriptor() ([]byte, []int) {
	return file_rpcPoc_proto_rawDescGZIP(), []int{1}
}

func (x *ResultByte) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rpcPoc_proto protoreflect.FileDescriptor

var file_rpcPoc_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x70, 0x63, 0x50, 0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68,
	0x0a, 0x1a, 0x45, 0x78, 0x65, 0x63, 0x50, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x42, 0x79, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xb8, 0x01, 0x0a, 0x04, 0x43,
	0x61, 0x6c, 0x6c, 0x12, 0x41, 0x0a, 0x13, 0x45, 0x78, 0x65, 0x63, 0x50, 0x79, 0x74, 0x68, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x12, 0x1b, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x50, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x42, 0x79, 0x74, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50,
	0x79, 0x74, 0x68, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x12, 0x1b,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x50, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x42, 0x79, 0x74, 0x65, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x0b, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x0b, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x42, 0x79, 0x74, 0x65, 0x1a, 0x0b, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42,
	0x79, 0x74, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x70, 0x6f, 0x63, 0x73,
	0x75, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpcPoc_proto_rawDescOnce sync.Once
	file_rpcPoc_proto_rawDescData = file_rpcPoc_proto_rawDesc
)

func file_rpcPoc_proto_rawDescGZIP() []byte {
	file_rpcPoc_proto_rawDescOnce.Do(func() {
		file_rpcPoc_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcPoc_proto_rawDescData)
	})
	return file_rpcPoc_proto_rawDescData
}

var file_rpcPoc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpcPoc_proto_goTypes = []interface{}{
	(*ExecPythonSerializeRequest)(nil), // 0: ExecPythonSerializeRequest
	(*ResultByte)(nil),                 // 1: ResultByte
}
var file_rpcPoc_proto_depIdxs = []int32{
	0, // 0: Call.ExecPythonSerialize:input_type -> ExecPythonSerializeRequest
	0, // 1: Call.CheckPythonSerialize:input_type -> ExecPythonSerializeRequest
	1, // 2: Call.healthCheck:input_type -> ResultByte
	1, // 3: Call.ExecPythonSerialize:output_type -> ResultByte
	1, // 4: Call.CheckPythonSerialize:output_type -> ResultByte
	1, // 5: Call.healthCheck:output_type -> ResultByte
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpcPoc_proto_init() }
func file_rpcPoc_proto_init() {
	if File_rpcPoc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcPoc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecPythonSerializeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcPoc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultByte); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcPoc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcPoc_proto_goTypes,
		DependencyIndexes: file_rpcPoc_proto_depIdxs,
		MessageInfos:      file_rpcPoc_proto_msgTypes,
	}.Build()
	File_rpcPoc_proto = out.File
	file_rpcPoc_proto_rawDesc = nil
	file_rpcPoc_proto_goTypes = nil
	file_rpcPoc_proto_depIdxs = nil
}
